load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "base",
    srcs = ["base.py"],
    imports = ["../../.."],
    visibility = [
        "//python/src:__subpackages__",
        "//python/tests:__subpackages__",
    ],
)
