# This directive tells Gazelle to use this dir (`src`) as the root python path.
# gazelle:python_root

# This directive tells Gazelle to append "//python/tests:__subpackages__" to the
# visibility of all python targets.
# gazelle:python_visibility //python/tests:__subpackages__
