# load("@rules_foreign_cc//toolchains/native_tools:native_tools_toolchain.bzl", "native_tool_toolchain")

# package(default_visibility = ["//visibility:public"])

# native_tool_toolchain(
#     name = "pkgconfig_impl",
#     path = "pkg-config",  # Expects executable name
#     target = "@pkg-config//:pkg-config",  # Hermetic target
# )

# toolchain(
#     name = "pkgconfig_toolchain",
#     toolchain = ":pkgconfig_impl",
#     toolchain_type = "@rules_foreign_cc//toolchains:pkgconfig_toolchain",
# )
