filegroup(
    name = "distribution",
    srcs = [
        # ":BUILD.bazel",
        # ":MODULE.bazel",
        # ":README.md",
        # ":WORKSPACE",
        ":def.bzl",
        ":deps.bzl",
        "//:go.mod",
        "//:go.sum",
        # "//manifest:distribution",
        # "//modules_mapping:distribution",
        # "//python:distribution",
        # "//pythonconfig:distribution",
    ],
    visibility = ["@monorepo//:__pkg__"],
)
